// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8s0S6Z-LKJO8AWrjMv-dop16F6mlS2Q',
    appId: '1:285444618426:web:3c67394feac1957c43aa83',
    messagingSenderId: '285444618426',
    projectId: 'investments-dashboard-clients',
    authDomain: 'investments-dashboard-clients.firebaseapp.com',
    storageBucket: 'investments-dashboard-clients.appspot.com',
    measurementId: 'G-HNKL649J3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Iuicgm1yfb4gLLDGOcLsAbLnqRObvDo',
    appId: '1:285444618426:android:f0da535bf067b7bf43aa83',
    messagingSenderId: '285444618426',
    projectId: 'investments-dashboard-clients',
    storageBucket: 'investments-dashboard-clients.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnl1q3E1aOJGI1izTXAta7XpLB0Qv-5qs',
    appId: '1:285444618426:ios:db84c85957452e9843aa83',
    messagingSenderId: '285444618426',
    projectId: 'investments-dashboard-clients',
    storageBucket: 'investments-dashboard-clients.appspot.com',
    iosBundleId: 'com.nuacventurecapital.bisonteapp',
  );
}
